### ISSUE TITLE
"goto" by itself seems to halt game

### ISSUE THREAD

**Issue by glassworm** [vcolavin/nature-of-the-beast#11]
<img width="355" alt="goto-heck" src="https://user-images.githubusercontent.com/43278397/56856188-18e8a500-690a-11e9-96c3-c8e8f8539858.png">

Edited to add browser:

<img width="637" alt="firefox" src="https://user-images.githubusercontent.com/43278397/56856203-58af8c80-690a-11e9-8139-88576ca34d23.png">

**Comment by vcolavin** [comment]
Thanks very much for reporting this! Fix coming in shortly.
