### ISSUE TITLE
Problem with reloading page

### ISSUE THREAD

**Issue by vcolavin** [vcolavin/nature-of-the-beast#2]
## To reproduce:

- Visit https://vcolavin.com/nature-of-the-beast/
- Reload page.

## Expected behavior:

Page reloads as normal.

## Actual behavior:

A 404 happens.

This has to do with the URL getting all switched dynamically by JavaScript. I don't know what the solution is to this offhand.

@complinggirl I will assign this issue to you once you accept the "collaborator" invite.

**Comment by vcolavin** [comment]
@complinggirl I've disabled the window location changing behavior for now with commit 4e5108a.

**Comment by complinggirl** [comment]
My understanding is that this could be avoided by using '#' instead of '/' as a prefix to appending the location to the url.  Unless you have some other advice, I'll try that.

**Comment by vcolavin** [comment]
Fixed with #3.
